# -*- coding: utf-8 -*-
"""Proyek_MLOps_ClimateChangeNews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FejuONtIntSKzVRKLsCuYx1RPjkYltvE

# Proyek MLOps : Climate Change Sentiment
- **Nama:** Abid Juliant Indraswara
- **Email:** abidjuliant@gmail.com
- **ID Dicoding:** abidindraswara

Fokus pada proyek ini adalah untuk membuat pipeline machine learning dengan topik machine learning yaitu sentimen berita mengenai perubahan iklim. Dataset yang digunakan adalah climate-change-news yang berasal dari Kaggle.

Dataset : https://www.kaggle.com/datasets/fringewidth/climate-change-news

## Install & Import Libray
"""

# Cek terlebih dahulu untuk mencoba upgrade pip di Google Colaboratory
try:
  import colab
  !pip install --upgrade pip
except:
  pass

# Install Lbrary TFX
!pip install -U tfx

# Install Library sesuai Kebutuhan
#!pip install -U tensorflow==2.13.0 tfx==1.14.0

# Melihat Summary dan Versi Library
!pip show numpy packaging google

# Koneksi ke Google Drive untuk Import Dataset
from google.colab import drive
drive.mount('/content/drive')

# Install Library Kaggle
!pip install kaggle

# Import Library Umum
import os, shutil
from shutil import copyfile
import zipfile
import pathlib
from pathlib import Path
import numpy as np
import pandas as pd

# Import Library untuk Machine Learning dan Pipeline
import tensorflow as tf
from tfx.components import CsvExampleGen, StatisticsGen, SchemaGen, ExampleValidator, Transform, Trainer, Tuner
from tfx.proto import example_gen_pb2
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
import os

# Upload File kaggle.json menggunakan token API akses melalui akun
from google.colab import files
files.upload()

# Hubungkan ke Kaggle melalui token API
!chmod 600 /content/kaggle.json

# Download Dataset .zip ke dalam Google Drive
# Source Dataset : https://www.kaggle.com/datasets/fringewidth/climate-change-news
!kaggle datasets download -d fringewidth/climate-change-news -p '/content/drive/My Drive/Dicoding_MachineLearning/Dicoding_MLPOps/MLOps_Project_1/'

# Cek Folder Dataset
!ls '/content/drive/My Drive/Dicoding_MachineLearning/Dicoding_MLPOps/MLOps_Project_1/'

# Membuat direktori baru untuk menampung dataset csv
!mkdir /content/climate_change_news

# Membuat direktori data untuk menampung dataset csv
!mkdir /content/climate_change_news/data

# Ekstrak Dataset dan Simpan ke Folder Data
zip_ref = zipfile.ZipFile("/content/drive/My Drive/Dicoding_MachineLearning/Dicoding_MLPOps/MLOps_Project_1/climate-change-news.zip", 'r')
zip_ref.extractall("/content/climate_change_news/data")
zip_ref.close()

# Rename File Sesuai Kebutuhan
old_file_name = "/content/climate_change_news/data/climate_headlines_sentiment.csv"
new_file_name = "/content/climate_change_news/data/data.csv"

# Rename File
os.rename(old_file_name, new_file_name)

# Tampilkan Hasil Apabila sudah Rename File
print(f"File renamed from {old_file_name} to {new_file_name}")

# Kode Program untuk Menghapus Folder di Google Colab
# import shutil

# # Ganti dengan path folder yang ingin dihapus
# folder_path = '/content/pipelines'
# # folder_path = '/content/pipelines/abidindraswara-pipeline/Transform'

# # Menghapus folder beserta isinya
# shutil.rmtree(folder_path)

# print(f"Folder {folder_path} telah dihapus beserta isinya.")

"""## Data Loading & Cek Dataset"""

# Dataset Climate Change News
climate_df = pd.read_csv("/content/climate_change_news/data/data.csv")
climate_df

# Mengubah Nilai Label -1 menjadi 0
data_path = "climate_change_news/data"
climate_df['Sentiment'] = climate_df['Sentiment'].replace({-1: 0})
climate_df.to_csv(os.path.join(data_path, "climate.csv"), index = False)

# Menghapus File untuk Menggantikan File yang Terbaru
file_path = "/content/climate_change_news/data/data.csv"

# Menghapus file
if os.path.exists(file_path):
    os.remove(file_path)
    print(f"File {file_path} telah dihapus.")
else:
    print(f"File {file_path} tidak ditemukan.")

# Menampilan Dataset yang sudah diproses
climate_df

# Cek NaN Dataset
print('Cek NaN Dataset Climate Change News')
print(climate_df.isna().sum())

# Cek Info Dataset
climate_df.info()

"""## Setup Init Pipeline"""

# Setup Nama Pipeline dan Variabel
PIPELINE_NAME = "abidindraswara-pipeline"
SCHEMA_PIPELINE_NAME = "abidindraswara-tfdv-schema"

# Direktori untuk Menyimpan Hasil Artifact dari masing-masing komponen
PIPELINE_ROOT = os.path.join('pipelines', PIPELINE_NAME)

# Path ke File SQLite DB yang digunakan untuk MLMD storage.
METADATA_PATH = os.path.join('metadata', PIPELINE_NAME, 'metadata.db')

# Output Direktori untuk ekspor pipeline hasil model yang sudah dibuat
SERVING_MODEL_DIR = os.path.join('serving_model', PIPELINE_NAME)

from absl import logging
logging.set_verbosity(logging.INFO)

# Set Folder Data
DATA_ROOT = "climate_change_news/data"

interactive_context = InteractiveContext(pipeline_root=PIPELINE_ROOT)

"""## Tahapan Komponen Data Ingestion"""

# Komponen Data Ingestion
# Pemilihan train dan eval 80:20 % Data

output = example_gen_pb2.Output(
    split_config = example_gen_pb2.SplitConfig(splits=[
        example_gen_pb2.SplitConfig.Split(name="train", hash_buckets=8),
        example_gen_pb2.SplitConfig.Split(name="eval", hash_buckets=2)
    ])
)
example_gen = CsvExampleGen(input_base=DATA_ROOT, output_config=output)

# Menampilkan Interactive Context Hasil example_gen
interactive_context.run(example_gen)

"""## Tahapan Komponen Data Validation"""

# Komponen Data Validation

statistics_gen = StatisticsGen(
    examples=example_gen.outputs["examples"]
)

interactive_context.run(statistics_gen)

interactive_context.show(statistics_gen.outputs["statistics"])

"""## Tahapan Komponen Data Schema"""

# Komponen Data Schema

schema_gen = SchemaGen(
    statistics=statistics_gen.outputs["statistics"]
)

interactive_context.run(schema_gen)

# Menampilkan Skema Data dan Cek Kolom
interactive_context.show(schema_gen.outputs["schema"])

"""## Tahapan Identifikasi Anomali Data

"""

example_validator = ExampleValidator(
    statistics=statistics_gen.outputs['statistics'],
    schema=schema_gen.outputs['schema']
)

interactive_context.run(example_validator)

# Menampilkan Hasil Cek Anomali Data
interactive_context.show(example_validator.outputs['anomalies'])

"""## Tahapan Komponen Data Transform"""

# Menetapkan Variabel Fungsi Preprocessing Data
TRANSFORM_MODULE_FILE = "climate_transform.py"

# Commented out IPython magic to ensure Python compatibility.
# # Membuat File Python yang Berisi Fungsi Preprocessing untuk Transform Data
# %%writefile {TRANSFORM_MODULE_FILE}
# import tensorflow as tf
# LABEL_KEY = "Sentiment"
# FEATURE_KEY = "Headline"
# def transformed_name(key):
#     """Renaming transformed features"""
#     return key + "_xf"
# def preprocessing_fn(inputs):
#     """
#     Preprocess input features into transformed features
# 
#     Args:
#         inputs: map from feature keys to raw features.
# 
#     Return:
#         outputs: map from feature keys to transformed features.
#     """
# 
#     outputs = {}
# 
#     outputs[transformed_name(FEATURE_KEY)] = tf.strings.lower(inputs[FEATURE_KEY])
# 
#     outputs[transformed_name(LABEL_KEY)] = tf.cast(inputs[LABEL_KEY], tf.int64)
# 
#     return outputs

# Komponen Transform
transform = Transform(
    examples=example_gen.outputs['examples'],
    schema= schema_gen.outputs['schema'],
    module_file=os.path.abspath(TRANSFORM_MODULE_FILE) # Melakukan Preprocessing dengan Fungsi climate_transform.py
)

interactive_context.run(transform)

"""## Tahapan Komponen Trainer"""

# Menetapkan Variabel Fungsi Trainer Berisi Model
TRAINER_MODULE_FILE = "climate_trainer.py"

# Commented out IPython magic to ensure Python compatibility.
# # Membuat File Python yang Berisi Fungsi Training Menggunakan Model
# %%writefile {TRAINER_MODULE_FILE}
# import tensorflow as tf
# import tensorflow_transform as tft
# from tensorflow.keras import layers
# import os
# import tensorflow_hub as hub
# from tfx.components.trainer.fn_args_utils import FnArgs
# 
# LABEL_KEY = "Sentiment"
# FEATURE_KEY = "Headline"
# 
# def transformed_name(key):
#     """Renaming transformed features"""
#     return key + "_xf"
# 
# def gzip_reader_fn(filenames):
#     """Loads compressed data"""
#     return tf.data.TFRecordDataset(filenames, compression_type='GZIP')
# 
# 
# def input_fn(file_pattern,
#              tf_transform_output,
#              num_epochs,
#              batch_size=64)->tf.data.Dataset:
#     """Get post_tranform feature & create batches of data"""
# 
#     # Get post_transform feature spec
#     transform_feature_spec = (
#         tf_transform_output.transformed_feature_spec().copy())
# 
#     # create batches of data
#     dataset = tf.data.experimental.make_batched_features_dataset(
#         file_pattern=file_pattern,
#         batch_size=batch_size,
#         features=transform_feature_spec,
#         reader=gzip_reader_fn,
#         num_epochs=num_epochs,
#         label_key = transformed_name(LABEL_KEY))
#     return dataset
# 
# # os.environ['TFHUB_CACHE_DIR'] = '/hub_chace'
# # embed = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4")
# 
# # Vocabulary size and number of words in a sequence.
# VOCAB_SIZE = 10000
# SEQUENCE_LENGTH = 100
# 
# vectorize_layer = layers.TextVectorization(
#     standardize="lower_and_strip_punctuation",
#     max_tokens=VOCAB_SIZE,
#     output_mode='int',
#     output_sequence_length=SEQUENCE_LENGTH)
# 
# 
# embedding_dim=16
# def model_builder():
#     """Build machine learning model"""
#     inputs = tf.keras.Input(shape=(1,), name=transformed_name(FEATURE_KEY), dtype=tf.string)
#     reshaped_narrative = tf.reshape(inputs, [-1])
#     x = vectorize_layer(reshaped_narrative)
#     x = layers.Embedding(VOCAB_SIZE, embedding_dim, name="embedding")(x)
#     x = layers.GlobalAveragePooling1D()(x)
#     x = layers.Dense(64, activation='relu')(x)
#     x = layers.Dense(32, activation="relu")(x)
#     outputs = layers.Dense(1, activation='sigmoid')(x)
# 
# 
#     model = tf.keras.Model(inputs=inputs, outputs = outputs)
# 
#     model.compile(
#         loss = 'binary_crossentropy',
#         optimizer=tf.keras.optimizers.Adam(0.01),
#         metrics=[tf.keras.metrics.BinaryAccuracy()]
# 
#     )
# 
#     # print(model)
#     model.summary()
#     return model
# 
# 
# def _get_serve_tf_examples_fn(model, tf_transform_output):
# 
#     model.tft_layer = tf_transform_output.transform_features_layer()
# 
#     @tf.function
#     def serve_tf_examples_fn(serialized_tf_examples):
# 
#         feature_spec = tf_transform_output.raw_feature_spec()
# 
#         feature_spec.pop(LABEL_KEY)
# 
#         parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
# 
#         transformed_features = model.tft_layer(parsed_features)
# 
#         # get predictions using the transformed features
#         return model(transformed_features)
# 
#     return serve_tf_examples_fn
# 
# def run_fn(fn_args: FnArgs) -> None:
# 
#     log_dir = os.path.join(os.path.dirname(fn_args.serving_model_dir), 'logs')
# 
#     tensorboard_callback = tf.keras.callbacks.TensorBoard(
#         log_dir = log_dir, update_freq='batch'
#     )
# 
#     es = tf.keras.callbacks.EarlyStopping(monitor='val_binary_accuracy', mode='max', verbose=1, patience=10)
#     mc = tf.keras.callbacks.ModelCheckpoint(fn_args.serving_model_dir, monitor='val_binary_accuracy', mode='max', verbose=1, save_best_only=True)
# 
# 
#     # Load the transform output
#     tf_transform_output = tft.TFTransformOutput(fn_args.transform_graph_path)
# 
#     # Create batches of data
#     train_set = input_fn(fn_args.train_files, tf_transform_output, 10)
#     val_set = input_fn(fn_args.eval_files, tf_transform_output, 10)
#     vectorize_layer.adapt(
#         [j[0].numpy()[0] for j in [
#             i[0][transformed_name(FEATURE_KEY)]
#                 for i in list(train_set)]])
# 
#     # Build the model
#     model = model_builder()
# 
# 
#     # Train the model
#     model.fit(x = train_set,
#             validation_data = val_set,
#             callbacks = [tensorboard_callback, es, mc],
#             steps_per_epoch = 1000,
#             validation_steps= 1000,
#             epochs=10)
#     signatures = {
#         'serving_default':
#         _get_serve_tf_examples_fn(model, tf_transform_output).get_concrete_function(
#                                     tf.TensorSpec(
#                                     shape=[None],
#                                     dtype=tf.string,
#                                     name='examples'))
#     }
#     model.save(fn_args.serving_model_dir, save_format='tf', signatures=signatures)

# Komponen Trainer
from tfx.proto import trainer_pb2

trainer  = Trainer(
    module_file=os.path.abspath(TRAINER_MODULE_FILE),
    examples = transform.outputs['transformed_examples'],
    transform_graph=transform.outputs['transform_graph'],
    schema=schema_gen.outputs['schema'],
    train_args=trainer_pb2.TrainArgs(splits=['train']),
    eval_args=trainer_pb2.EvalArgs(splits=['eval'])
)
interactive_context.run(trainer)

"""## Tahapan Komponen Analisis dan Validasi Model"""

# Komponen Resolver
from tfx.dsl.components.common.resolver import Resolver
from tfx.dsl.input_resolution.strategies.latest_blessed_model_strategy import LatestBlessedModelStrategy
from tfx.types import Channel
from tfx.types.standard_artifacts import Model, ModelBlessing

model_resolver = Resolver(
    strategy_class= LatestBlessedModelStrategy,
    model = Channel(type=Model),
    model_blessing = Channel(type=ModelBlessing)
).with_id('Latest_blessed_model_resolver')

interactive_context.run(model_resolver)

# Berikut Fungsi untuk Mengevaluasi Model Sesuai dengan Metric yang Dipilih
import tensorflow_model_analysis as tfma

# LABEL_KEY = "Sentiment"
# FEATURE_KEY = "Headline"

eval_config = tfma.EvalConfig(
    model_specs=[tfma.ModelSpec(label_key='Sentiment')],
    slicing_specs=[tfma.SlicingSpec()],
    metrics_specs=[
        tfma.MetricsSpec(metrics=[

            tfma.MetricConfig(class_name='ExampleCount'),
            tfma.MetricConfig(class_name='AUC'),
            tfma.MetricConfig(class_name='FalsePositives'),
            tfma.MetricConfig(class_name='TruePositives'),
            tfma.MetricConfig(class_name='FalseNegatives'),
            tfma.MetricConfig(class_name='TrueNegatives'),
            tfma.MetricConfig(class_name='BinaryAccuracy',
                threshold=tfma.MetricThreshold(
                    value_threshold=tfma.GenericValueThreshold(
                        lower_bound={'value':0.5}),
                    change_threshold=tfma.GenericChangeThreshold(
                        direction=tfma.MetricDirection.HIGHER_IS_BETTER,
                        absolute={'value':0.0001})
                    )
            )
        ])
    ]

)

# Komponen Evaluator

from tfx.components import Evaluator
evaluator = Evaluator(
    examples=example_gen.outputs['examples'],
    model=trainer.outputs['model'],
    baseline_model=model_resolver.outputs['model'],
    eval_config=eval_config
)

interactive_context.run(evaluator)

print(evaluator.inputs)

interactive_context.run(evaluator)

# Visualize the evaluation results
eval_result = evaluator.outputs['evaluation'].get()[0].uri
tfma_result = tfma.load_eval_result(eval_result)
tfma.view.render_slicing_metrics(tfma_result)
tfma.addons.fairness.view.widget_view.render_fairness_indicator(
    tfma_result
)

"""## Tahapan Komponen Pusher"""

from tfx.components import Pusher
from tfx.proto import pusher_pb2

pusher = Pusher(
    model=trainer.outputs['model'],
    model_blessing=evaluator.outputs['blessing'],
    push_destination=pusher_pb2.PushDestination(
    filesystem=pusher_pb2.PushDestination.Filesystem(
        base_directory='serving_model_dir/climate-changes-news-model'))

)

interactive_context.run(pusher)

# Komponen Pusher

from tfx.components import Pusher
from tfx.proto import pusher_pb2

pusher = Pusher(
    model=trainer.outputs['model'],
    model_blessing=evaluator.outputs['blessing'],
    push_destination=pusher_pb2.PushDestination(
    filesystem=pusher_pb2.PushDestination.Filesystem(
        base_directory='serving_model_dir/climate-changes-news-model'))

)

interactive_context.run(pusher)

# Export Mode dan Pipeline
!zip -r pipelines.zip pipelines/
!zip -r serving_model_dir.zip serving_model_dir/
!pip freeze > requirements.txt

# Download Folder Pipeline
import shutil
from google.colab import files

# folder_path = '/content/pipelines/abidindraswara-pipeline'
folder_path = '/content/serving_model_dir/climate-changes-news-model'

zip_filename = '/content/climate-changes-news-model.zip'

shutil.make_archive(zip_filename.replace('.zip', ''), 'zip', folder_path)

files.download(zip_filename)

!pip freeze requirements.txt